package View;

import Model.DBConnection;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.Reader;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.tools.FileObject;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author hctha_000
 */
public class addtuFileTxt extends javax.swing.JFrame {

    public int type; //type = 0 : thêm đọc giả, type = 1 : thêm sách ,type = 2 : thêm quyển

    public addtuFileTxt() {
        initComponents();
        setTitle("Thêm Độc Giả Từ File Txt - Phần mềm quản lí thư viện");
        setExtendedState(MAXIMIZED_BOTH);
        this.setVisible(true);
    }

    void showWindows() {

        this.setExtendedState(MAXIMIZED_BOTH);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jFileChooser1 = new javax.swing.JFileChooser();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Đăng xuất");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 1183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(201, Short.MAX_VALUE))
        );

        File  dir = new File("D:\\Documents-Hoctap\\Project1\\CSDL_QuanLiThuVien");
        jFileChooser1.setCurrentDirectory(dir);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            int countTrue = 0,countTotal = 0;
            FileInputStream fileInPutStream = new FileInputStream(jFileChooser1.getSelectedFile());
            Reader reader = new java.io.InputStreamReader(fileInPutStream, "Unicode");
            BufferedReader buffReader = new BufferedReader(reader);
            String line = null;

            
            if (type == 1) {
                while ((line = buffReader.readLine()) != null) {
                    if (insertSach(line)) {
                        countTrue++;
                    }
                    countTotal++;
                }
            }
            if (type == 0) {
                while ((line = buffReader.readLine()) != null) {
                    if (insertDocGia(line)) {
                        countTrue++;
                    }
                    countTotal++;
                }
            }
            
            if (type == 2) {
                while ((line = buffReader.readLine()) != null) {
                    if (insertQuyen(line)) {
                        countTrue++;
                    }
                    countTotal++;
                }
            }

            JOptionPane.showMessageDialog(null, "Đã thêm " + countTrue + "/" + countTotal + " bản ghi");

            //Đóng kết nối với file.
            reader.close();

        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, ex);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex);

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        LoginForm newlogin = new LoginForm();
        newlogin.showWindows();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        this.dispose();
        if (type == 0) {
            QuanLiDocGia newQuanLiDocGia = new QuanLiDocGia();
            newQuanLiDocGia.showWindows();
        }
        if (type == 1 || type == 2) {
            QuanLiSach newQuanLiSach = new QuanLiSach();
            newQuanLiSach.showWindows();
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addtuFileTxt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addtuFileTxt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addtuFileTxt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addtuFileTxt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addtuFileTxt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private boolean insertDocGia(String line) {
        try {
            String[] docGia = new String[10];
            for (int i = 0; i < 9; i++) {
                docGia[i] = line.substring(0, line.indexOf(",", 0));
                line = line.substring(line.indexOf(",", 0) + 1);
            }

            String sqlAddDocGia = "INSERT INTO DocGia (MaDocGia, TenDocGia, Mssv, Lop, Khoa, GioiTinh, NgaySinh, Sdt, DiaChi, NgayTao) VALUES ( '"
                    + docGia[0].trim() + "','"
                    + docGia[1].trim() + "',"
                    + docGia[2].trim() + ",'"
                    + docGia[3].trim() + "','"
                    + docGia[4].trim() + "','"
                    + docGia[5].trim() + "','"
                    + docGia[6].trim() + "','"
                    + docGia[7].trim() + "','"
                    + docGia[8].trim() + "','"
                    + line.trim() + "');";

            DBConnection dbAddDocGia = new DBConnection();
            dbAddDocGia.getConnection();
            dbAddDocGia.state.execute(sqlAddDocGia);
            System.out.println(sqlAddDocGia);
            return true; // đã thêm thành công
        } catch (SQLException ex) {
            System.out.println("Thêm bản ghi thất bại");
        }
        return false; //thêm thất bại
    }

    private boolean insertSach(String line) {
        try {
            String[] sach = new String[8];
            for (int i = 0; i < 7; i++) {
                sach[i] = line.substring(0, line.indexOf(",", 0));
                line = line.substring(line.indexOf(",", 0) + 1);
            }

            String sqlAddSach = "INSERT INTO Sach (MaSach, TenSach, Gia, Nxb, NamXB, TacGia, TheLoai, SoTrang) VALUES ( '"
                    + sach[0].trim() + "','"
                    + sach[1].trim() + "',"
                    + sach[2].trim() + ",'"
                    + sach[3].trim() + "',"
                    + sach[4].trim() + ",'"
                    + sach[5].trim() + "','"
                    + sach[6].trim() + "',"
                    + line.trim() + ");";

            DBConnection dbAddSach = new DBConnection();
            dbAddSach.getConnection();
            dbAddSach.state.execute(sqlAddSach);
            System.out.println(sqlAddSach);
            return true; // đã thêm thành công
        } catch (SQLException ex) {
            System.out.println("Thêm bản ghi thất bại");
        }
        return false; //thêm thất bại
    }

    private boolean insertQuyen(String line) {
        try {
            String[] quyen = new String[4];
            for (int i = 0; i < 3; i++) {
                quyen[i] = line.substring(0, line.indexOf(",", 0));
                line = line.substring(line.indexOf(",", 0) + 1);
            }

            String sqlAddQuyen = "INSERT INTO ChiTietSach (MaSach, MaQuyen, NgayNhap, TrangThai) VALUES ( '"
                    + quyen[0].trim() + "','"
                    + quyen[1].trim() + "','"
                    + quyen[2].trim() + "','"
                    + line.trim() + "');";

            DBConnection dbAddQuyen = new DBConnection();
            dbAddQuyen.getConnection();
            dbAddQuyen.state.execute(sqlAddQuyen);
            System.out.println(sqlAddQuyen);
            return true; // đã thêm thành công
        } catch (SQLException ex) {
            System.out.println("Thêm bản ghi thất bại");
        }
        return false; //thêm thất bại
    }

}
