package View;

import Model.DBConnection;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class LoginForm extends javax.swing.JFrame {

    public LoginForm() {

        initComponents();
        setTitle("Đăng Nhập - Phần mềm quản lí thư viện");
        Model.ThuVien.initData(true,"no","C:\\Users\\hctha_000\\Documents\\NetBeansProjects\\QuanLiThuVien\\src\\Model\\QuanLiThuVien.sql");
        
    }
    public void showWindows(){
		//this.setSize(600,600);
		this.setDefaultCloseOperation(EXIT_ON_CLOSE);
		this.setResizable(false);
		this.setLocationRelativeTo(null);
		this.setVisible(true);
	}

    public static String librarianLogin(String user_name, String pass_word) {
        if(user_name.equals("root") && pass_word.equals("123")) return "librarian";
        //user : root, pass : 123
        return "failed";
    }
    public static String studentLogin(String mssv, String MaDocGia) {

        try {
            DBConnection dbConn = new DBConnection();
            dbConn.getConnection();
            //user : MSSV, pass : MaDocGia
            String strSQL = "SELECT * FROM DocGia WHERE Mssv = '"
                    + mssv + "' AND MaDocGia = '" + MaDocGia +"';";
            
            dbConn.excuteQuery(strSQL);
            if (dbConn.result.next() == false) {
                return "failed";
            } else {
                return dbConn.result.getString("TenDocGia");
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
        
        return "failed";
    }

    public void checkLogin() {
        String user = jTextField1.getText();
        String pass = jPasswordField1.getText();
        {
            
            if (librarianLogin(user, pass).equals("librarian")) {
                JOptionPane.showMessageDialog(null, "Welcome Thủ Thư");
                this.dispose();
                LibrarianForm loginSuccesful = new LibrarianForm();
                loginSuccesful.showWindows();
            } else if(!studentLogin(user, pass).equals("failed")){ //user : MSSV, pass : MaDocGia
                JOptionPane.showMessageDialog(null, "Welcome " +studentLogin(user, pass));
                this.dispose();
                DocGiaForm loginSuccesful = new DocGiaForm(pass);
                loginSuccesful.showWindows();
            }else {
            JOptionPane.showMessageDialog(null, "Login failed");
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nen = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 200));
        setMinimumSize(new java.awt.Dimension(829, 340));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(312, 62, 240, 30);

        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyPressed(evt);
            }
        });
        jPanel1.add(jPasswordField1);
        jPasswordField1.setBounds(312, 137, 240, 30);

        jLabel1.setText("Độc giả đăng nhập bằng");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(600, 210, 150, 40);

        jLabel2.setText("MSSV và Mã Độc Giả");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(610, 240, 120, 30);

        nen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photo/login form.jpg"))); // NOI18N
        jPanel1.add(nen);
        nen.setBounds(10, 0, 800, 296);

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(263, 196, 293, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 807, 311);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        checkLogin();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            checkLogin();
        }
        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            jTextField1.requestFocus();
        }
    }//GEN-LAST:event_jPasswordField1KeyPressed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            checkLogin();
        }
        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            jPasswordField1.requestFocus();
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LoginForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel nen;
    // End of variables declaration//GEN-END:variables
}
